project:
  type: website
  output-dir: public

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "lost-triangle.com"
        href: "https://lost-triangle.com"
  sidebar:
    contents: 
      - text: "Einleitung"
        href: src/01_getting_started/intro.md

      - section: "Animationsprojekte"
        href: src/02_development/intro.md
        contents: 
          - text: "Projektmanagement"
            href: src/02_development/project-managment.md
          - text: "Projektmanagement Beispiel"
            href: src/02_development/03_ProjectManagmentBeispiel.md
          - text: "Wie bekommt man Ideen?"
            href: src/02_development/04_Wie_Bekommt_Man_Ideen.md
          - text: "Animation Pipeline"
            href: src/02_development/05_AnimationPipeline.md 
      - section: "Maya Grundlagen"
        href: src/03_maya_basics/00_intro.md
        contents:
          - text: "Maya UI"
            href: src/03_maya_basics/01_MayaUI.md
          - text: "Einstellungen"
            href: src/03_maya_basics/02_Einstellungen.md
          - text: "Keyboard Shortcuts"
            href: src/03_maya_basics/03_KeyboardShortcuts.md
          - text: "Render Engines"
            href: src/03_maya_basics/04-RenderEngines.md
          - text: "Grundlagen 3D"
            href: src/03_maya_basics/04_Grundlagen_3D.md
          - text: "Wine Glass"
            href: src/03_maya_basics/05_WineGlass.md
      - section: "Modelling"
        href: src/04_modelling/04_modelling.md
        

      - section: "Modelling mit NURBS"
        href: src/04a_modelling-nurbs/00_modelling-nurbs.md
        contents:
          - text: "Maya UI NURBS"
            href: src/04a_modelling-nurbs/01_MayaUINurbs.md
          - text: "NURBS Grundlagen"
            href: src/04a_modelling-nurbs/02_NURBSGrundlagen.md
          - text: "Curves Grundlagen"
            href: src/04a_modelling-nurbs/03_CurvesGrundlagen.md
          - text: "Bezier Grundlagen"
            href: src/04a_modelling-nurbs/04_BezierGrundlagen.md
          - text: "Curve Tools"
            href: src/04a_modelling-nurbs/05_CurveTools.md
          - text: "Surface Tools"
            href: src/04a_modelling-nurbs/06_SurfaceTools.md
          - text: "Praxis Tisch"
            href: src/04a_modelling-nurbs/07_PraxisTisch.md
          - text: "Praxis Stuhl"
            href: src/04a_modelling-nurbs/08_PraxisStuhl.md
          - text: "Tesselation"
            href: src/04a_modelling-nurbs/10_Tesselation.md
      - section: "Modelling mit Polygonen"
        href: src/04b_modelling-polygon/00_modelling-polygon.md
        contents: 
          - text: "Maya UI Polygon"
            href: src/04b_modelling-polygon/01-MayaUIPoly.md
          - text: "Polygon Grundlagen"
            href: src/04b_modelling-polygon/02-PolygonGrundlagen.md
          - text: "Polygon Tools"
            href: src/04b_modelling-polygon/03-PolygonTools.md
          - text: "DNA"
            href: src/04b_modelling-polygon/04-DNA.md
          - text: "Plane"
            href: src/04b_modelling-polygon/05-Plane.md
          - text: "Modelling Anmerkungen"
            href: src/04c_modelling-anmerkungen/04c_modelling-anmerkungen.md
      - section: "Camera"
        href: src/05_camera/00_camera.md
        contents: 
          - text: "Camera"
            href: src/05_camera/01_Camera.md
          - text: "Arbeiten mit Cameras"
            href: src/05_camera/02_ArbeitenMitCameras.md
          - text: "Einzelbild Komposition"
            href: src/05_camera/03_EinzelbildKomposition.md
          - text: "Kamera Animation"
            href: src/05_camera/07_KameraAnimation.md
      - section: "Lighting"
        href: src/06_lighting/00_title.md
        contents: 
          - text: "Maya UI Lights"
            href: src/06_lighting/01_MayaUILights.md
          - text: "CG Licht"
            href: src/06_lighting/02_CGLicht.md
          - text: "Grundlagen Schatten"
            href: src/06_lighting/03_GrundlagenSchatten.md
          - text: "Grundlagen Indirekt Lighting"
            href: src/06_lighting/04_GrundlagenIndirektLighting.md
          - text: "Beleuchtungs Überlegungen"
            href: src/06_lighting/05_BeleuchtungsUeberlegungen.md
          - text: "Test Render Lighting"
            href: src/06_lighting/09_TestRenderLighting.md
      - section: "Shading"
        href: src/07_shading/00_shading.md
        contents: 
          - text: "Shading UI"
            href: src/07_shading/01_ShadingUI.md
          - text: "Shader Basics"
            href: src/07_shading/02_ShaderBasics.md
          - text: "Maya Basic"
            href: src/07_shading/03_MayaBasic.md
          - text: "Arnold Shader"
            href: src/07_shading/04_ArnoldShader.md
      - section: "Animation"
        href: src/08_animation/00_animation.md
        contents: 
          - text: "UI Animation"
            href: src/08_animation/01_UIAnimation.md
          - text: "Grundlagen"
            href: src/08_animation/02_Grundlagen.md
          - text: "Graph Editor"
            href: src/08_animation/03_GraphEditor.md
          - text: "Keyframe Animation"
            href: src/08_animation/04_KeyframeAnimation.md
          - text: "Motion Path"
            href: src/08_animation/05_MotionPath.md
          - text: "Reactive Animation"
            href: src/08_animation/06_ReactiveAnimation.md
          - text: "Expression Editor"
            href: src/08_animation/07_ExpressionEditor.md
          - text: "Inverse Kinematics"
            href: src/08_animation/08_InverseKinematics.md
      - section: "Rendering"
        href: src/09_rendering/00_rendering.md
        contents: 
          - text: "General"
            href: src/09_rendering/01_General.md
          - text: "Animation Einstellungen"
            href: src/09_rendering/02_AnimationEinstellungen.md
      - section: "Anhang"
        href: src/10_appendix/00a_anhang.md
        contents: 
          - text: "Scripting"
            href: src/10_appendix/01_Scripting.md
          - text: "Resources"
            href: src/10_appendix/02-Resources.md
          - text: "Non Arnold Lights"
            href: src/10_appendix/05-NonArnoldLights.md
          - text: "Shading"
            href: src/10_appendix/07-Shading.md
      - section: "Abgabe"
        href: src/11_submission/b_abgabe.md
        contents: 
          - text: "Checkliste"
            href: src/11_submission/checklist.md
book:
  title: "Introduction to Maya"
  author: "Neal Burger"
  date: "2026-02-23"
  downloads: [pdf, epub]

  chapters:
    - part: "Einleitung"
      chapters:
        - src/01_getting_started/intro.md
    - part: "Animationsprojekte"
      chapters:
        - src/02_development/intro.md
        - src/02_development/project-managment.md
        - src/02_development/03_ProjectManagmentBeispiel.md
        - src/02_development/04_Wie_Bekommt_Man_Ideen.md
        - src/02_development/05_AnimationPipeline.md
    - part: "Maya Grundlagen"
      chapters:
        - src/03_maya_basics/00_intro.md
        - src/03_maya_basics/01_MayaUI.md
        - src/03_maya_basics/02_Einstellungen.md
        - src/03_maya_basics/03_KeyboardShortcuts.md
        - src/03_maya_basics/04-RenderEngines.md
        - src/03_maya_basics/04_Grundlagen_3D.md
        - src/03_maya_basics/05_WineGlass.md
    - part: "Modelling"
      chapters:
        - src/04_modelling/04_modelling.md
    - part: "Modelling mit NURBS"
      chapters:
        - src/04a_modelling-nurbs/00_modelling-nurbs.md
        - src/04a_modelling-nurbs/01_MayaUINurbs.md
        - src/04a_modelling-nurbs/02_NURBSGrundlagen.md
        - src/04a_modelling-nurbs/03_CurvesGrundlagen.md
        - src/04a_modelling-nurbs/04_BezierGrundlagen.md
        - src/04a_modelling-nurbs/05_CurveTools.md
        - src/04a_modelling-nurbs/06_SurfaceTools.md
        - src/04a_modelling-nurbs/07_PraxisTisch.md
        - src/04a_modelling-nurbs/08_PraxisStuhl.md
        - src/04a_modelling-nurbs/10_Tesselation.md
    - part: "Modelling mit Polygonen"
      chapters:
        - src/04b_modelling-polygon/00_modelling-polygon.md
        - src/04b_modelling-polygon/01-MayaUIPoly.md
        - src/04b_modelling-polygon/02-PolygonGrundlagen.md
        - src/04b_modelling-polygon/03-PolygonTools.md
        - src/04b_modelling-polygon/04-DNA.md
        - src/04b_modelling-polygon/05-Plane.md
        - src/04c_modelling-anmerkungen/04c_modelling-anmerkungen.md
    - part: "Camera"
      chapters:
        - src/05_camera/00_camera.md
        - src/05_camera/01_Camera.md
        - src/05_camera/02_ArbeitenMitCameras.md
        - src/05_camera/03_EinzelbildKomposition.md
        - src/05_camera/07_KameraAnimation.md
    - part: "Lighting"
      chapters:
        - src/06_lighting/00_title.md
        - src/06_lighting/01_MayaUILights.md
        - src/06_lighting/02_CGLicht.md
        - src/06_lighting/03_GrundlagenSchatten.md
        - src/06_lighting/04_GrundlagenIndirektLighting.md
        - src/06_lighting/05_BeleuchtungsUeberlegungen.md
        - src/06_lighting/09_TestRenderLighting.md
    - part: "Shading"
      chapters:
        - src/07_shading/00_shading.md
        - src/07_shading/01_ShadingUI.md
        - src/07_shading/02_ShaderBasics.md
        - src/07_shading/03_MayaBasic.md
        - src/07_shading/04_ArnoldShader.md
    - part: "Animation"
      chapters:
        - src/08_animation/00_animation.md
        - src/08_animation/01_UIAnimation.md
        - src/08_animation/02_Grundlagen.md
        - src/08_animation/03_GraphEditor.md
        - src/08_animation/04_KeyframeAnimation.md
        - src/08_animation/05_MotionPath.md
        - src/08_animation/06_ReactiveAnimation.md
        - src/08_animation/07_ExpressionEditor.md
        - src/08_animation/08_InverseKinematics.md
    - part: "Rendering"
      chapters:
        - src/09_rendering/00_rendering.md
        - src/09_rendering/01_General.md
        - src/09_rendering/02_AnimationEinstellungen.md
    - part: "Anhang"
      chapters:
        - src/10_appendix/00a_anhang.md
        - src/10_appendix/01_Scripting.md
        - src/10_appendix/02-Resources.md
        - src/10_appendix/05-NonArnoldLights.md
        - src/10_appendix/07-Shading.md
    - part: "Abgabe"
      chapters:
        - src/11_submission/b_abgabe.md
        - src/11_submission/checklist.md

format:
  html:
    theme: litera
    code-link: true
    author-meta: "Neal Burger"
  pdf:
    documentclass: memoir
  epub:
    theme: default
